In [5]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [17]:
arr=np.random.randint(1, 255,size=(5,5))

In [18]:
arr

array([[113,  13, 221, 225,  63],
       [247, 186, 242,  80, 109],
       [233,  43, 238,  58, 236],
       [ 98,  51,  46, 169, 218],
       [202, 166, 129, 147,  24]])

In [19]:
arr-100

array([[ 13, -87, 121, 125, -37],
       [147,  86, 142, -20,   9],
       [133, -57, 138, -42, 136],
       [ -2, -49, -54,  69, 118],
       [102,  66,  29,  47, -76]])

In [20]:
b = np.array([[1],[2],[3]])
a = np.array([1,2,3])
b-a

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

In [21]:
Series(data=[1,2,3])

0    1
1    2
2    3
dtype: int64

In [24]:
Series(data=[1,2,3], index=['a', 'b','c'])

a    1
b    2
c    3
dtype: int64

In [36]:
Series(data=np.random.randint(1,10, size=10))

0    7
1    1
2    6
3    2
4    4
5    7
6    6
7    6
8    2
9    9
dtype: int64

In [59]:
s1 = Series(range(1,11))
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [63]:
s = Series([1,1,2,2,3,4,5,5,5,5,5])
s

0     1
1     1
2     2
3     2
4     3
5     4
6     5
7     5
8     5
9     5
10    5
dtype: int64

In [61]:
s.unique()

array([1, 2, 3, 4, 5])

In [64]:
s1 -s

0     0.0
1     1.0
2     1.0
3     2.0
4     2.0
5     2.0
6     2.0
7     3.0
8     4.0
9     5.0
10    NaN
dtype: float64

In [65]:
pd.isnull(s1-s)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [67]:
(s1-s).isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [71]:
(s1-s)[(s1-s).notnull()]

0    0.0
1    1.0
2    1.0
3    2.0
4    2.0
5    2.0
6    2.0
7    3.0
8    4.0
9    5.0
dtype: float64

In [77]:
s = Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [78]:
s[0:3]

a    1
b    2
c    3
dtype: int64

In [79]:
s[::2]

a    1
c    3
dtype: int64

In [80]:
s['a':'b']

a    1
b    2
dtype: int64

In [81]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [87]:
s.loc['a':'b']

a    1
b    2
dtype: int64

In [84]:
s.iloc[0:3]

a    1
b    2
c    3
dtype: int64

In [88]:
s.values

array([1, 2, 3, 4])

In [89]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [90]:
s.size

4

In [91]:
s.shape

(4,)

In [92]:
s.head(2)

a    1
b    2
dtype: int64

In [93]:
s.tail(2)

c    3
d    4
dtype: int64

In [94]:
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [95]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [96]:
s1 + s

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [99]:
s1.add(s, fill_value = 0)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
a     1.0
b     2.0
c     3.0
d     4.0
dtype: float64

In [100]:
s1.sub(s, fill_value=0)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
a    -1.0
b    -2.0
c    -3.0
d    -4.0
dtype: float64

In [105]:
s1.mod(s,fill_value=1)

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
5    0.0
6    0.0
7    0.0
8    0.0
9    0.0
a    0.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [8]:
df=DataFrame(data=np.random.randint(0,100, size=(3,3)), index=('a', 'b', 'c'), columns=('1', '2', '3'))
df

1   2   3
a  29  46  91
b   1  43  27
c  17  45  87

In [93]:
df[['1','2']]

1   2
a  29  46
b   1  43
c  17  45

In [86]:
df.loc[['a','c'], ['1', '2']]

1   2
a  29  46
c  17  45

In [111]:
df.shape

(3, 3)

In [112]:
df.size

9

In [113]:
df.index

Index(['a', 'b', 'c'], dtype='object')

In [114]:
df.columns

Index(['1', '2', '3'], dtype='object')

In [115]:
df.values

array([[13, 75, 52],
       [ 5, 93, 84],
       [48, 62, 42]])

In [116]:
dic = {
    '张三':[11,22,33,44],
    '李四':[55,66,77,88]
}
df_score = DataFrame(data=dic,index=['语文','数学','英语','理综'])

In [117]:
df_score

张三  李四
语文  11  55
数学  22  66
英语  33  77
理综  44  88

In [4]:
dic = {
    '张三':[4,5,6],
    '李四':[1,2,3]
}
DataFrame(dic, index=['语文', '英语', '数学'])

NameError: name 'DataFrame' is not defined

In [119]:
df=DataFrame(data=np.random.randint(0,100, size=(3,3)), index=('a', 'b', 'c'), columns=('1', '2', '3'))
df

1   2   3
a  34  40  46
b  32  94  86
c  58  69  45

In [128]:
df[['1','2']]

1   2
a  34  40
b  32  94
c  58  69

SyntaxError: invalid syntax (<ipython-input-131-2f0a8bd4aaec>, line 1)

In [136]:
df=DataFrame(np.random.randint(0,100, size=(3,3)), index=('a','b','c'), columns=('A','B','C'))
df.A
type(df.A)

pandas.core.series.Series

In [142]:
df

A   B   C
a   0  44  68
b  14   4   6
c  42  73  44

In [150]:
df.loc[['a', 'c'], 'C']

a    68
c    44
Name: C, dtype: int64

In [152]:
df['A']

a     0
b    14
c    42
Name: A, dtype: int64

In [155]:
df.loc[['a','b']]

A   B   C
a   0  44  68
b  14   4   6

In [156]:
df.iloc[[0, 1]]

A   B   C
a   0  44  68
b  14   4   6

In [157]:
df.loc['a', 'C']

68

In [172]:
df[0:2]
df.iloc[:,0:2]

A   B
a   0  44
b  14   4
c  42  73

In [173]:
df + df

A    B    C
a   0   88  136
b  28    8   12
c  84  146   88

In [174]:
df[['A', 'B']]

A   B
a   0  44
b  14   4
c  42  73

In [260]:
import tushare as ts
import pandas as pd

In [257]:
df = ts.get_k_data(code='600519', start='2000')
df.to_csv('./test.csv')

In [265]:
df = pd.read_csv('./test.csv', index_col='date', parse_dates=True)
df.head(5)
df.drop(labels=['Unnamed: 0'], axis=1, inplace=True)

In [266]:
df.index[0]

Timestamp('2001-08-27 00:00:00')

In [267]:
df.head(4)

open  close   high    low     volume    code
date                                                     
2001-08-27  5.392  5.554  5.902  5.132  406318.00  600519
2001-08-28  5.467  5.759  5.781  5.407  129647.79  600519
2001-08-29  5.777  5.684  5.781  5.640   53252.75  600519
2001-08-30  5.668  5.796  5.860  5.624   48013.06  600519

In [270]:
df[(df.open - df.close)/df.close > 0.03].index

DatetimeIndex(['2001-10-10', '2001-11-07', '2001-11-16', '2001-12-20',
               '2002-01-04', '2002-01-17', '2002-01-28', '2002-04-17',
               '2002-11-08', '2003-01-02',
               ...
               '2018-02-07', '2018-04-27', '2018-06-19', '2018-06-27',
               '2018-07-02', '2018-08-17', '2018-10-08', '2018-10-10',
               '2018-10-23', '2019-07-03'],
              dtype='datetime64[ns]', name='date', length=178, freq=None)

In [274]:
df[(df.open - df.close.shift(1))/df.close.shift(1) < -0.02].index

DatetimeIndex(['2001-09-12', '2002-06-26', '2002-12-13', '2004-07-01',
               '2004-10-29', '2006-08-21', '2006-08-23', '2007-01-25',
               '2007-02-01', '2007-02-06', '2007-03-19', '2007-05-21',
               '2007-05-30', '2007-06-05', '2007-07-27', '2007-09-05',
               '2007-09-10', '2008-03-13', '2008-03-17', '2008-03-25',
               '2008-03-27', '2008-04-22', '2008-04-23', '2008-04-29',
               '2008-05-13', '2008-06-10', '2008-06-13', '2008-06-24',
               '2008-06-27', '2008-08-11', '2008-08-19', '2008-09-23',
               '2008-10-10', '2008-10-15', '2008-10-16', '2008-10-20',
               '2008-10-23', '2008-10-27', '2008-11-06', '2008-11-12',
               '2008-11-20', '2008-11-21', '2008-12-02', '2009-02-27',
               '2009-03-25', '2009-08-13', '2010-04-26', '2010-04-30',
               '2011-08-05', '2012-03-27', '2012-08-10', '2012-11-22',
               '2012-12-04', '2012-12-24', '2013-01-16', '2013-01-25',
      

In [290]:
new_df = df['2010':'2019']
df_monthly = new_df.resample('M').first()
df_monthly

open     close      high       low     volume    code
date                                                                 
2010-01-31   109.760   108.446   109.760   108.044   44304.88  600519
2010-02-28   107.769   107.776   108.216   106.576   29655.94  600519
2010-03-31   106.219   106.085   106.857   105.925   21734.74  600519
2010-04-30   101.324   102.141   102.422   101.311   23980.83  600519
2010-05-31    81.676    82.091    82.678    80.974   23975.16  600519
2010-06-30    84.075    84.637    85.166    83.278   23525.57  600519
2010-07-31    81.586    81.057    81.586    80.725    7449.69  600519
2010-08-31    89.296    92.465    93.567    89.296   42965.73  600519
2010-09-30   102.288   101.052   103.834   100.420   25589.00  600519
2010-10-31   108.858   111.776   113.045   108.858   31608.00  600519
2010-11-30   105.122   105.483   106.217   104.478   49658.00  600519
2010-12-31   130.759   130.372   133.980   128.839   38016.00  600519
2011-01-31   120.388   119.487   121.033   117.619   60462.00  600519
2011-02-28   114.656   116.124   117.136   114.334   17758.00  600519
2011-03-31   115.113   115.068   115.899   114.527   23059.00  600519
2011-04-30   115.931   115.596   116.813   115.010   18227.00  600519
2011-05-31   117.876   119.718   120.324   117.232   41270.00  600519
2011-06-30   131.467   135.197   135.255   130.772   39093.00  600519
2011-07-31   137.895   137.272   137.895   136.033   15810.00  600519
2011-08-31   148.519   145.689   148.519   145.274   18572.00  600519
2011-09-30   153.798   151.491   154.357   150.789   25689.00  600519
2011-10-31   136.735   134.672   137.394   134.407   14283.00  600519
2011-11-30   145.546   148.418   148.640   145.066   27147.00  600519
2011-12-31   152.724   152.466   154.149   150.625   33785.00  600519
2012-01-31   137.179   132.716   138.089   132.523   33878.00  600519
2012-02-29   133.382   133.347   135.044   132.437   24824.00  600519
2012-03-31   145.789   145.116   147.186   144.980   16920.00  600519
2012-04-30   140.474   147.566   147.852   140.474   40960.00  600519
2012-05-31   161.893   161.878   162.301   159.027   35339.00  600519
2012-06-30   170.489   172.187   174.071   169.565   38504.00  600519
...              ...       ...       ...       ...        ...     ...
2017-04-30   374.595   378.480   383.657   373.954   40789.00  600519
2017-05-31   399.791   400.257   403.093   397.440   23291.00  600519
2017-06-30   429.804   436.390   437.040   428.357   40604.00  600519
2017-07-31   460.595   447.161   460.595   444.762   49628.00  600519
2017-08-31   474.266   473.517   476.238   470.716   27501.00  600519
2017-09-30   483.337   488.248   489.332   483.170   31451.00  600519
2017-10-31   517.196   520.381   528.052   512.819   34891.00  600519
2017-11-30   612.188   614.288   622.698   610.551   43435.00  600519
2017-12-31   629.078   613.637   630.044   611.448   47192.00  600519
2018-01-31   690.200   693.996   700.218   680.232   49612.00  600519
2018-02-28   756.262   747.122   756.558   742.379   50582.00  600519
2018-03-31   717.808   731.582   736.394   713.637   44794.00  600519
2018-04-30   670.480   670.539   681.326   664.673   32039.00  600519
2018-05-31   650.760   658.480   659.624   636.029   70259.00  600519
2018-06-30   740.614   734.679   744.410   728.417   36177.00  600519
2018-07-31   734.520   711.550   739.330   703.000   37558.00  600519
2018-08-31   731.400   714.940   732.300   714.110   25237.00  600519
2018-09-30   652.000   666.210   667.670   650.800   30179.00  600519
2018-10-31   715.410   686.150   719.000   686.150   82745.00  600519
2018-11-30   555.000   563.000   585.500   551.250   98106.00  600519
2018-12-31   589.000   601.200   605.000   584.770   83414.00  600519
2019-01-31   609.980   598.980   612.000   595.010   62286.00  600519
2019-02-28   697.040   692.670   699.000   689.610   30520.00  600519
2019-03-31   761.500   789.300   790.000   761.000   63840.00  600519
2019-04-30   860.000   859

In [291]:
df_yearly = new_df.resample('A').last()[:-1]
df_yearly

open    close     high      low   volume    code
date                                                           
2010-12-31  117.103  118.469  118.701  116.620  46084.0  600519
2011-12-31  138.039  138.468  139.600  136.105  29460.0  600519
2012-12-31  155.208  152.087  156.292  150.144  51914.0  600519
2013-12-31   93.188   96.480   97.179   92.061  57546.0  600519
2014-12-31  157.642  161.056  161.379  157.132  46269.0  600519
2015-12-31  207.487  207.458  208.704  207.106  19673.0  600519
2016-12-31  317.239  324.563  325.670  317.239  34687.0  600519
2017-12-31  707.948  687.725  716.329  681.918  76038.0  600519
2018-12-31  563.300  590.010  596.400  560.000  63678.0  600519

In [292]:
cost = df_monthly.open.sum() * 100
cost

3453686.0999999996

In [293]:
recv = df_yearly.open.sum() * 1200
recv

2948584.7999999993

In [294]:
new_df.open[-1:]*900 + recv - cost

date
2019-09-03    520898.7
Name: open, dtype: float64

In [295]:
df

open     close      high       low     volume    code
date                                                                 
2001-08-27     5.392     5.554     5.902     5.132  406318.00  600519
2001-08-28     5.467     5.759     5.781     5.407  129647.79  600519
2001-08-29     5.777     5.684     5.781     5.640   53252.75  600519
2001-08-30     5.668     5.796     5.860     5.624   48013.06  600519
2001-08-31     5.804     5.782     5.877     5.749   23231.48  600519
2001-09-03     5.812     5.779     5.870     5.757   22112.09  600519
2001-09-04     5.782     5.852     5.949     5.762   37006.77  600519
2001-09-05     5.876     5.849     5.924     5.813   26066.95  600519
2001-09-06     5.835     5.734     5.854     5.704   28997.03  600519
2001-09-07     5.702     5.574     5.773     5.570   31552.25  600519
2001-09-10     5.531     5.734     5.757     5.470   18878.89  600519
2001-09-11     5.749     5.670     5.773     5.656   11390.81  600519
2001-09-12     5.520     5.621     5.656     5.515   25045.19  600519
2001-09-13     5.626     5.607     5.671     5.577   10986.68  600519
2001-09-14     5.626     5.671     5.702     5.593    7672.83  600519
2001-09-17     5.637     5.599     5.670     5.546    8983.97  600519
2001-09-18     5.606     5.663     5.710     5.601   10773.26  600519
2001-09-19     5.671     5.768     5.768     5.634    8650.53  600519
2001-09-20     5.765     5.720     5.788     5.702   11173.35  600519
2001-09-21     5.668     5.634     5.718     5.624    7879.72  600519
2001-09-24     5.634     5.632     5.685     5.624    4068.60  600519
2001-09-25     5.668     5.660     5.709     5.632    3488.45  600519
2001-09-26     5.642     5.637     5.699     5.624    4956.26  600519
2001-09-27     5.637     5.734     5.777     5.624    8778.04  600519
2001-09-28     5.765     5.795     5.812     5.702   17088.47  600519
2001-10-08     5.781     5.715     5.809     5.663    6552.17  600519
2001-10-09     5.718     5.827     5.859     5.718    9558.52  600519
2001-10-10     5.827     5.640     5.848     5.629   17548.69  600519
2001-10-11     5.626     5.585     5.702     5.570   12306.84  600519
2001-10-12     5.609     5.624     5.726     5.320   20010.70  600519
...              ...       ...       ...       ...        ...     ...
2019-07-24   958.310   946.360   959.900   944.690   46771.00  600519
2019-07-25   945.970   963.000   963.360   938.150   38255.00  600519
2019-07-26   961.970   965.030   971.000   958.550   26467.00  600519
2019-07-29   962.030   976.410   979.500   960.010   26981.00  600519
2019-07-30   976.500   978.930   983.000   971.000   19537.00  600519
2019-07-31   975.000   972.600   981.770   966.590   22526.00  600519
2019-08-01   976.510   959.300   977.000   953.020   35089.00  600519
2019-08-02   944.000   954.450   957.980   943.000   39719.00  600519
2019-08-05   945.000   942.430   954.000   940.000   36774.00  600519
2019-08-06   931.000   946.300   948.000   923.800   43991.00  600519
2019-08-07   949.500   945.000   955.530   945.000   26869.00  600519
2019-08-08   953.500   971.680   974.000   952.000   38808.00  600519
2019-08-09   978.500   962.030   980.950   958.990   28461.00  600519
2019-08-12  1010.310  1018.630  1020.100   995.010   81498.00  600519
2019-08-13  1016.160  1017.950  1026.000  1010.680   30329.00  600519
2019-08-14  1030.020  1043.330  1051.900  1030.020   41410.00  600519
2019-08-15  1028.000  1044.900  1046.480  1028.000   27237.00  600519
2019-08-16  1049.840  1054.600  1075.580  1041.000   36086.00  600519
2019-08-19  1061.000  1055.880  1069.980  1049.050   32867.00  600519
2019-08-20  1055.000  1070.000  1073.680  1050.000   28602.00  600519
2019-08-21  1070.100  1066.000  1076.970  1061.660   25066.00  600519
2019-08-22  1072.990  1104.000  1104.000  1070.000   37590.00  600519
2019-08-23  1105.000  1130.100  1133.560  1095.620   40192.00  600519
2019-08-26  1113.000  1102.950  1128.000  1096.680   48497.00  600519
2019-08-27  1117.000  1109